before_script:
  - apt-get update
  - apt-get install -y libnuma-dev libibverbs-dev

build:
  only:
  - tags
  script:
  - "./autogen.sh"
  - "./contrib/configure-release"
  - make
  - make dist
  - 'export upload_url=$(curl -s -H "Authorization: token $github_token" "https://api.github.com/repos/openucx/ucx/releases/latest" | grep upload_url | grep -oP "https\S+assets")'
  - 'export tar_name=$(ls *.tar.gz)'
  - 'curl -s -H "Authorization: token $github_token" -H "Content-Type: application/zip" --data-binary @"$tar_name" "${upload_url}?name=${tar_name}&label=${tar_name}"'

