parameters:
  worker_ids: [0, 1, 2, 3]
  num_workers: 4
  demands: []
  name: subtest

jobs:
  - job: tests
    pool:
      name: MLNX
      demands: ${{ parameters.demands }}
    displayName: ${{ parameters.name }} on worker
    timeoutInMinutes: 240
    strategy:
      matrix:
        ${{ each wid in parameters.worker_ids }}:
          ${{ wid }}:
            worker_id: ${{ wid }}
    variables:
      executor_number: 1
    steps:
      # Agent name is expected to be like 'hostname-<id>'. Since one
      # azure agent == one job, this number is uniq on the host with multiple
      # agents on it.
      - bash: |
          executor_from_agent_name=$(echo $AGENT_NAME | awk -F- '{print $NF}' | sed 's/^0*//g')
          echo "##vso[task.setvariable variable=executor_number]$executor_from_agent_name"
          echo "EXECUTOR_NUMBER=$executor_from_agent_name"
      - bash: |
          ./contrib/test_jenkins.sh || echo "there are fails"
        env:
          nworkers: ${{ parameters.num_workers }}
          worker: $(worker_id)
          BUILD_NUMBER: "$(Build.BuildId)-$(Build.BuildNumber)"
          JOB_URL: "$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)"
          EXECUTOR_NUMBER: $(executor_number)
          JENKINS_RUN_TESTS: 1
          JENKINS_TEST_PERF: 0
