parameters:
  worker_ids: [0, 1, 2, 3]
  num_workers: 4
  demands: []
  name: subtest

jobs:
  - job: tests
    pool:
      name: MLNX
      demands: ${{ parameters.demands }}
    displayName: ${{ parameters.name }} on worker
    timeoutInMinutes: 240
    strategy:
      matrix:
        ${{ each wid in parameters.worker_ids }}:
          ${{ wid }}:
            worker_id: ${{ wid }}
    steps:
      - bash: |
          ./contrib/test_jenkins.sh
        displayName: Run ./contrib/test_jenkins.sh
        env:
          nworkers: ${{ parameters.num_workers }}
          worker: $(worker_id)
          BUILD_NUMBER: "$(Build.BuildId)-$(Build.BuildNumber)"
          JOB_URL: "$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)"
          JENKINS_RUN_TESTS: ""
          EXECUTOR_NUMBER: $(AZP_AGENT_ID)
          RUN_TESTS: yes
          JENKINS_TEST_PERF: 0

