parameters:
  - name: demands
    type: string
    default: "ucx_iodemo -equals yes"
  - name: test_duration
    type: number
    default: 2
  - name: tests
    type: object
    default:
      base:
        # Disable corrupter for master branch
        initial_delay: 2000
        cycles: 100
        downtime: 5
        uptime: 40

jobs:
  - job: io_build
    displayName: Build io_demo

    pool:
      name: MLNX
      demands: ${{ parameters.demands }}

    steps:
      # address permissions issue when some files created as read-only
      - bash: chmod u+rwx ./ -R

      - checkout: self
        clean: true
        displayName: Checkout
      - bash: |
          set -eEx
          ./autogen.sh
          ./contrib/configure-release --prefix=$(Build.Repository.LocalPath)/install
          make -j`nproc`
          make install
          echo "##vso[task.setvariable variable=workspace;isOutput=true]$(Build.Repository.LocalPath)/buildlib"
          echo "##vso[task.setvariable variable=io_demo_exe;isOutput=true]$(Build.Repository.LocalPath)/install/bin/io_demo"
        displayName: Build
        name: build

  - job: test
    dependsOn: io_build

    pool:
      name: MLNX
      demands: ${{ parameters.demands }}

    strategy:
      matrix:
        ${{ each test in parameters.tests }}:
          ${{ test.Key }}:
            test_name: ${{ test.Key }}
            initial_delay: ${{ test.Value.initial_delay }}
            cycles: ${{ test.Value.cycles }}
            downtime: ${{ test.Value.downtime }}
            uptime: ${{ test.Value.uptime }}
      maxParallel: 1

    variables:
      workspace: $[ dependencies.io_build.outputs['build.workspace'] ]
      io_demo_exe: $[ dependencies.io_build.outputs['build.io_demo_exe'] ]

    displayName: "io_demo: "
    steps:
      - checkout: none
      - template: az-stage-io-demo.yaml
        parameters:
          name: tag
      - template: az-stage-io-demo.yaml
        parameters:
          name: active
          iodemo_args: -q -A
